# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool: ordenador-personal

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g firebase-tools
  displayName: 'npm install'

- script: |
    npm run build
  displayName: 'build'

- script: |
    firebase deploy --token $(FIREBASE_TOKEN)
  displayName: 'despliegue'